spring:
  application:
    name: product
  data:
    mongodb:
      uri: ${env.MONGO_URI}
      database: ${env.MONGO_DATABASE}

server:
  port: 8001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka